### ISSUE TITLE
iDeal issuers list placement error

### ISSUE THREAD

**Issue by Ylmzef** [mollie/magento2-scandipwa#9]
iDeal issuers list loading above of the checkout button when select iDeal as payment methode.
It's normally loading under the iDeal area like as on Luma template.

Also QR (qr-select.svg) image file is missing.

![Schermafbeelding 2022-09-10 om 18 18 07](https://user-images.githubusercontent.com/8562514/189492432-5cbbd5d9-83ad-4625-9ac5-132d2cf40672.png)

**Comment by Frank-Magmodules** [comment]
Hello @Yllmzef,

Thanks for opening this issue. The QR code image will be fixed in the next release of the **main** Mollie repository ([https://github.com/mollie/magento2](https://github.com/mollie/magento2)). The placement of the list of issuers is dictated by ScandiPWA. The “CheckoutPayment” component is placed below the list of payment methods. We have no influence on this.
